tasks:
  - init: npm install --prefix ./sources && npm run dev --prefix ./sources
vscode:
  extensions:
    - octref.vetur
    - ecmel.vscode-html-css
    - dbaeumer.vscode-eslint
ports:
  - port: 8080
    name: Dev Web Preview
    description: Development Preview or robotframework.org
    onOpen: notify
    visibility: public